### get my ip
#@name myIp
#@mock {"origin":"127.0.0.1"}
GET http://{{host}}/ip

### Post test
#@name postTest
< {%
    request.variables.set("nick", "linux_china");
%}
POST https://{{host}}/post
Content-Type: application/json

{
  "hello": "{{nick}}"
}

### graphql test
#@name graphqlTest
GRAPHQL https://graphqlzero.almansi.me/api

query demo($id: ID!) {
   post(id: $id) {
       id
       title
       body
     }
}

{
  "id": 1
}

