### get my ip
//@name myIp
GET https://httpbin.org/ip

### Post test
//@name postTest
POST https://httpbin.org/post
Content-Type: application/json

{
  "hello": "{{nick}}"
}

### graphql test
//@name graphqlTest
GRAPHQL https://localhost:8787/graphql

query demo($nick: String!) {
   welcome(name : $nick )
}

{
  "nick": "{{nick}}"
}

